### ISSUE TITLE
Conclusion lines 583 - 586

### ISSUE THREAD

**Issue by cavaglia** [PhoenixBirdCreations/IPAM2021_ML#18]
Complete sentences in conclusion: 

The decrease in performance for HasRem between O2 and O3 of both algorithms may be attributed
to RF [. . . ] The lower performance of RF across different pipelines compared to KNN may be explained by [. . . ]

**Comment by frenbox** [comment]
Random forest classifier is a decision tree based classifier where the decision rules (for classification) places specific cuts (conditions) on the input features. K-Nearest Neighbor, on the other hand, computes nearest neighbors in the training set around a specific point of interest in the parameter space of input features.

We found that the Random Forest classifier performs better than KNN, as seen in the ROC curves, in the testing data set of O2 GstLAL for both HasNS and HasRemnant. However on the O3 MDC dataset containing 3 additional CBC pipelines, RF showed more variation in ROC curve among the pipelines compared to KNN. The RF performance for HasRemnant in O3 GstLAL is consistent with O2 dataset but under-performs sightly for other 3 pipelines. We think(In this case) that the decision tree based alogrithm (RF) is not equally portable across pipelines as much has KNN.

The nature of RF algorithm might be suitable for HasNS classifier which benefits from learning right cuts (conditions) on the secondary mass feature. For HasRemnant algorithms tries to the Foucart equation curve that differentiates non zero with zero post Remnant merger mass. While both algorithms can learn this boundary (as seen in O2 dataset), due to algorithmic nature, RF is less portable for other pipelines compared to KNN.

Do we need to address the spirr gap for HasNS

I am just writing my thoughts out loud. Need your help to summarize this and put it in conclusion.

**Comment by miqmiq** [comment]
I agree with the explanation of RF underperforming when it comes to other pipelines. I like the third paragraph, in which you give extra details about what RF exactly does.

Regarding the gap with spiir, it happens to both KNN and RF, so I would say we need further investigation.

**Comment by miqmiq** [comment]
@frenbox could you also add a summary of this explanation in the results or modify what's already there? Just where these plots are explained (paragraph starting at line 475).
