### ISSUE TITLE
Check accuracy of conclusions

### ISSUE THREAD

**Issue by cavaglia** [PhoenixBirdCreations/IPAM2021_ML#20]
Please check accuracy of paragraph 556 - 578. Make sure all statements are correct.

**Comment by miqmiq** [comment]
I looked for the plots comparing the performances of the current LVK KNN and ours, but I couldn't find them. @PhoenixBirdCreations , do you have any prove that our algorithms perform better than the current KNN? I remember they did, but I can't find the plots.

**Comment by PhoenixBirdCreations** [comment]
That would be the plots that we did to compare with Deep's paper. The histograms and the roc curves colored by threshold. Those plots have to be in the repository, because we have looked plenty at them. The histograms were definetly better, and the roc curves too if we keep it in the testing dataset, as they do. The thing is in our paper we are focusing now on the Bayesian probabilities and we are no longer plotting to compare directly with Deep's. So in the testing set we are better, but in the paper we are writting we are not showing the proof right now..

Maybe, instead of using plots for the direct comparison, we can do an analogous to table 3 in Deep's paper. I know we wrote it some time ago and we had better TP and FP.  It doesn't occupy a lot of space and we can say that is for direct comparison with previous works

**Comment by miqmiq** [comment]
We don't want to show any extra plot, but we are stating that our algorithms perform better than the current KNN and we need some proofs just in case somebody asks about this. It's okay if we only use the scores, since it is what is being used in the LVK.

**Comment by PhoenixBirdCreations** [comment]
Then yes, take the table that we commented out in the paper with the TP and FP. That's enough to make that affirtmation

**Comment by miqmiq** [comment]
That one only includes our KNN and RF, do you know where the results with Deep's KNN are? I cannot find them.

**Comment by PhoenixBirdCreations** [comment]
[1911.00116.pdf](https://github.com/PhoenixBirdCreations/IPAM2021_ML/files/12781191/1911.00116.pdf)
table 3

**Comment by miqmiq** [comment]
okay, now I understand. Thanks!

**Comment by lmagana3** [comment]
I'll have to give the plots another look later, but I just went through all and it looks good to me.

**Comment by cavaglia** [comment]
Please all make sure all statements in the current version are accurate

**Comment by miqmiq** [comment]
I think conclusions are fine

**Comment by PhoenixBirdCreations** [comment]
Looks good
