### ISSUE TITLE
Some more issues after corrections

### ISSUE THREAD

**Issue by frenbox** [PhoenixBirdCreations/IPAM2021_ML#37]
- Line 293-294 equation number is missing.
- Line 356, **The value of HasRem label for NSBH depends on ...** this sentence is true but so are BBH and BNS. We should either add add BBH and BNS in the mix or just remove this sentence.
- Line 383, is that sentence correct?
- Line 456, are we using "worse" ?
- Paragraph 457. Is the statement correct? 
- Line 480, **System's component mass ...**, Implication of this sentence seems unclear.
- Line 579, may be add based on **differences of its neighbors **

**Comment by cavaglia** [comment]
This will have to be implemented after PnP. For the three questions, please propose new wording.

**Comment by miqmiq** [comment]
> * Line 293-294 equation number is missing. 
Agree with this. 
> * Line 356, **The value of HasRem label for NSBH depends on ...** this sentence is true but so are BBH and BNS. We should either add add BBH and BNS in the mix or just remove this sentence.
That's true, I would remove it, since it's obvious that the labels depend on the choice of the EOS. 
> * Line 383, is that sentence correct?
It's not, I would remove "the latter" since we only mention one data set, D_S. I would say "and use this set to calculate"
> * Line 456, are we using "worse" ?
We can do it the other way around: "RF performs similarly to KNN for GstLAL but KNN outperforms RF for the other pipelines".
> * Paragraph 457. Is the statement correct?
I think it is, but again we say "worse" (line 461).  I would say instead "but it does not on HasNS". 
> * Line 480, **System's component mass ...**, Implication of this sentence seems unclear.
Maybe we could say that it's more due to the fact that the secondary mass is close to the NS maximum mass threshold. 
> * Line 579, may be add based on **differences of its neighbors **
Agree.
